---
title: "deseqF2"
author: "Carolina Monzo"
date: "9/1/2021"
output: html_document
---
```{r}
suppressPackageStartupMessages(library(dada2))
suppressPackageStartupMessages(library(phyloseq))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(phangorn))
suppressPackageStartupMessages(library(DECIPHER))
suppressPackageStartupMessages(library(vegan))
suppressPackageStartupMessages(library(DESeq2))
suppressPackageStartupMessages(library(tidyr))
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(Biostrings))
suppressPackageStartupMessages(library(ANCOMBC))
suppressPackageStartupMessages(library(mvabund))
library(microbial)
theme_set(theme_bw())
setwd("~/workspace/16S_final/CM_16S_cross-sectionalF245/scripts/")
project_path <- "~/workspace/16S_final/CM_16S_cross-sectionalF245/"
new_day <- gsub("-", "", as.character(Sys.Date()))
metadata <- read.table("../metadata/metadata_F245_16S.csv", sep = ";", header = T, row.names = 1, stringsAsFactors = F, comment.char = "")
ps <- readRDS("../analysis/seqtab_merge3/phyloseq_obj_20210625.rds")
```

```{r DESeq2}
## Differential expression
# Store data in "../analysis/deseq_timepoints/"
# Format sampledata
sample_data(ps)$Treatment <- as.factor(sample_data(ps)$Treatment)
sample_data(ps)$Months <- as.numeric(sample_data(ps)$Months)
sample_data(ps)$ID <- as.factor(sample_data(ps)$ID)
# Subset AL/DR
aldr_comp <- subset_samples(ps, Treatment %in% c("AL_lifelong", "DR_lifelong"))
# Timepoints to the maximum before reaching only 1 mouse alive of the shortest lived group
timepoint <- c(5, 20, 24, 26)
for (i in 1:length(timepoint)){
  # Subset for months
  comp <- subset_samples(aldr_comp, Months == timepoint[[i]])
  
  ds <- phyloseq_to_deseq2(comp, ~Treatment)
  
  # Since these tables have zeroes
  # calculate geometric means prior to estimate size factors
  gm_mean = function(x, na.rm=TRUE){
    exp(sum(log(x[x > 0]), na.rm=na.rm) / length(x))
  }
  geoMeans = apply(counts(ds), 1, gm_mean)
  
  ds = estimateSizeFactors(ds, geoMeans = geoMeans)
  ds = DESeq(ds, fitType="local", test="Wald")
  
  res <- results(ds)
  alpha <- 0.05
  sigtab <- res[which(res$padj < alpha), ]
  sigtab <- cbind(as(sigtab, "data.frame"), as(tax_table(ps)[rownames(sigtab), ], "matrix"))
  
  write.table(sigtab, paste0(project_path, "/analysis/deseq_timepoints/ALDR_", timepoint[[i]], "M_", new_day, ".csv"), sep=";", quote=F, col.names=NA)
}
```

```{r}
# Check that all our timepoints have OTUs fitting to negative binomial and can therefore be analyzed by deseq2
for (i in 1:length(timepoint)){
  comp <- subset_samples(aldr_comp, Months == timepoint[[i]])
  nb <- manyglm(otu_table(comp) ~ sample_data(comp)$Treatment, family = "negative_binomial")
  pdf(paste0("../analysis/plots/deseq_timepoints/neg_binom_", timepoint[[i]], "_M_", new_day, ".pdf"))
  plot(nb)
  dev.off()
}
```